### ISSUE TITLE
Please attach into releases section compiled client

### ISSUE THREAD

**Issue by serhii-eleks** [tleyden/open-ocr-client#4]
Hello,

Could you please attach into releases section compiled client. I can't build this project. Looks like API of dependencies changed. But I want to use this client as sample to convert on Java. Specially for upload image API.

Thanks.

**Comment by tleyden** [comment]
Hey @serhii-eleks.  Thanks for the suggestion, and I agree that would be a nice feature.  However I think that it's easy enough to build from source or extract it from the docker container (or just use it via docker), that this is very low on the priority list.

Let me know if you need any help using either of the above approaches.
